spring.couchbase.connection-string=${COUCHBASE_HOST:localhost}
spring.couchbase.username=${COUCHBASE_USERNAME:Administrator}
spring.couchbase.password=${COUCHBASE_PASSWORD:password}
spring.data.couchbase.bucket-name=${COUCHBASE_BUCKET:demo}
spring.data.couchbase.auto-index=true

server.port=8080
